<?php

/**
 * @file
 * The main checksum module file. Contains most of the hook implementations.
 *
 * @todo Add uninstall hook to delete our the variables we set.
 */

/**
 * Implements hook_menu().
 */
function islandora_checksum_menu() {
  $items = array();
  $items['admin/islandora/checksum'] = array(
    'title' => 'Checksum',
    'description' => 'Configure the Islandora Checksum creator.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_checksum_admin_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_islandora_datastream_alter().
 */
function islandora_checksum_islandora_datastream_alter(AbstractObject $object, AbstractDatastream $datastream, &$context) {
  if (variable_get('islandora_checksum_enable_checksum', FALSE) && in_array($context['action'], array('ingest', 'modify'))) {
    $datastream->checksumType = variable_get('islandora_checksum_checksum_type', 'DISABLED');
  }
}
