<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_checksum_uninstall() {
  $variables = array(
    'islandora_checksum_checksum_type',
    'islandora_checksum_enable_checksum',
    'islandora_checksum_log_retro_errors',
    'islandora_checksum_dsids_to_check',
    'islandora_checksum_use_dsid_filter_retro',
  );
  array_walk($variables, 'variable_del');
}
